# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
pipelines:
  branches:
    master:
      - step:
          name: Build RabbitCLI Application
          image: mcr.microsoft.com/dotnet/sdk:5.0
          script:
            - dotnet restore RabbitMQ.Toolbox.sln
            - dotnet build --no-restore RabbitMQ.Toolbox.sln
  custom:
    publish-win-app:
      - step:
          name: Build and publish RabbitCLI
          image: mcr.microsoft.com/dotnet/sdk:5.0
          caches:
            - node
          script:
            - dotnet restore src/RabbitMQ.CLI/RabbitMQ.CLI.csproj
            - dotnet build --no-restore src/RabbitMQ.CLI/RabbitMQ.CLI.csproj
            - dotnet publish --no-build --self-contained true -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true src/RabbitMQ.CLI/RabbitMQ.CLI.csproj -o ./publish
          artifacts:
            - publish/rabbitcli.exe