name: Publish Windows-x64

on: workflow_dispatch

jobs:
  get-tag-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Write version into file
      run: grep -oP "(<Version>).*(</Version>)" src/RabbitMQ.CLI/RabbitMQ.CLI.csproj | awk -F '[><]' '{print $3}' > artifact/version
    - name: Save Version File
      uses: actions/upload-artifact@v2
      with:
        name: docker-tag-version
        path: ./artifact/
  build-docker-compose:
    needs: docker-tag-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: docker-tag-version
        path: docker-tag
    - name: Display structure of downloaded files
      run: ls -Rla
      working-directory: ./
    - name: Get version string
      id: version
      run: echo "::set-output name=version::$(cat docker-tag/version)"
    - name: Output version
      run: echo Got version - $VERSION
      env:
        VERSION: ${{ steps.version.outputs.version }}
    - name: Build & Tag image
    
  
