name: Publish Windows-x64

on: workflow_dispatch

jobs:
  publish-win-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore RabbitMQ.Toolbox.sln
    - name: Build
      run: dotnet build --no-restore RabbitMQ.Toolbox.sln
    - name: Publish application for win-x64
      run: dotnet publish --no-build --self-contained true -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true src/RabbitMQ.CLI/RabbitMQ.CLI.csproj -o ./publish
    - name: Copy install.ps1 to publish dir
      run: cp install.ps1 publish/install.ps1
    - name: Write version into file
      run: grep -oP "(<Version>).*(</Version>)" src/RabbitMQ.CLI/RabbitMQ.CLI.csproj | awk -F '[><]' '{print $3}' > publish/version
    - name: Save Published Files
      uses: actions/upload-artifact@v2
      with:
        name: publish-win-x64
        path: ./publish/
  push-releases:
    needs: publish-win-x64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: publish-win-x64
        path: win-x64
    - name: Display structure of downloaded files
      run: ls -Rla
      working-directory: ./
    - name: Get version string
      id: version
      run: echo "::set-output name=version::$(cat win-x64/version)"
    - name: Output version
      run: echo Got version - $VERSION
      env:
        VERSION: ${{ steps.version.outputs.version }}
    - name: Install zip
      uses: montudor/action-zip@v1
    - name: Pack published files for win-x64
      run: zip -qq -r RabbitCLI-${{ steps.version.outputs.version }}.zip win-x64/install.ps1 win-x64/rabbitcli.exe
    - uses: actions/checkout@v2
      name: Checkout releases branch
      with:
        ref: releases
        path: repo
    - name: Copy archive
      run: cp RabbitCLI*.zip repo/win-x64/
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        path: repo
        delete-branch: true
        branch: release/rabbitcli
        title: New Release of RabbitCLI
        commit-message: Adds new release-package
        body: |
          Adds new release-package
          [Created automatically]
  
