name: .NET

on: workflow_dispatch
    
jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore RabbitMQ.Toolbox.sln
    - name: Build
      run: dotnet build --no-restore RabbitMQ.Toolbox.sln
    - name: Publish application for win-x64
      run: dotnet publish --no-build --self-contained true -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true src/RabbitMQ.CLI/RabbitMQ.CLI.csproj -o ./publish
    - name: Save Published Files
      uses: actions/upload-artifact@v2
      with:
        name: publish-win-x64
        path: ./publish/
  store-artifacts:
    needs: buildAndPublish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: publish-win-x64
        path: win-x64
    - name: Display structure of downloaded files
      run: ls -Rla
      working-directory: ./
