name: .NET

on: workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore RabbitMQ.Toolbox.sln
    - name: Build
      run: dotnet build --no-restore RabbitMQ.Toolbox.sln
    - name: Test
      run: dotnet test --no-build RabbitMQ.Toolbox.sln
  publish-windows:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Publish application for win-x64
      run: dotnet publish --no-build --self-contained true -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true src/RabbitMQ.CLI/RabbitMQ.CLI.csproj -o ./publish
    - name: Display structure of published files
      run: ls -laR
      working-directory: ./publish
    - uses: actions/upload-artifact@v2
      with:
        name: win-app
        path: ./publish/
  store-artifacts:
    needs: publish-windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: win-app
        path: artifacts
    - name: Display structure of downloaded files
      run: ls -Rla
      working-directory: artifacts
